language: ruby
rvm:
  - "2.1.2"
services:
  - mongodb
  - redis-server
bundler_args: --without development:production --path vendor/bundle
before_install:
  - gem update bundler --no-rdoc --no-ri --pre
before_script:
  - bundle exec rake db:create db:migrate
script: bundle exec rake
notifications:
  webhooks:
    - https://idobata.io/hook/7f233190-cc78-41e5-a002-507e01d762a8
